### ISSUE TITLE
Debug issues with source-airtable connector

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte-Hackathon#10]
## Summary

The Airtable source is having issues when run in PyAirbyte. The goal is to replicate and document any observed issues and then propose a fix.

## Resources to Assist
- PyAirbyte tutorials: https://github.com/airbytehq/quickstarts/tree/main/pyairbyte_notebooks
- PyAirbyte Documentaton: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started 
- PyAirbyte API Reference: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started#api-reference
- Source-linkedin-ads documentation: https://docs.airbyte.com/integrations/sources/linkedin-ads

**Comment by puru-khedre** [comment]
Hello @aaronsteers, Please give it to me, I wanted to work on it

**Comment by marcosmarxm** [comment]
Hello @puru-khedre do you need any help?

**Comment by marcosmarxm** [comment]
@puru-khedre the idea is to see if you are able to run a sync using the `source-airtable` using PyAirbyte. If when you try get any error the idea is to report them here.

**Comment by fvgm-spec** [comment]
Hi @puru-khedre and @marcosmarxm I was reading a bit about this issue, and I think I can work on it, I currently work on a daily basis with Airtable datasets and Airtable API, could I take it or collaborate on this issue?

**Comment by marcosmarxm** [comment]
@puru-khedre let's @fvgm-spec work on this and select another one issue.

**Comment by marcosmarxm** [comment]
@fvgm-spec all yours

**Comment by fvgm-spec** [comment]
I have followed these steps to debug syncing data stored in Airtable using the `source-airtable` PyAirbyte connector:

1. Loaded some data in Airtable using Airteble API:

![Image](https://github.com/airbytehq/PyAirbyte-Hackathon/assets/60470663/5caf9381-d76a-4551-9f23-7d456b772dda)

2. Once data is loaded into Airtable:

![Image](https://github.com/airbytehq/PyAirbyte-Hackathon/assets/60470663/8eb5ad70-5cf2-4171-84d9-c1fdea15cbc8)

3. I have tried to sync with the data source using pyairbyte

![Image](https://github.com/airbytehq/PyAirbyte-Hackathon/assets/60470663/e17943a9-4d33-4a26-83dc-72462ce6a5e1)

4. I have previously set the variables for `personal_access_token`, `refresh_token`, `client_id` and `client_secret`, but still getting a syncing error:

![Image](https://github.com/airbytehq/PyAirbyte-Hackathon/assets/60470663/609bcae6-b2ad-4ea4-bdb8-341a05064fcd)

![Image](https://github.com/airbytehq/PyAirbyte-Hackathon/assets/60470663/0591ffd2-7a68-47d7-9f80-cea5a7af14d5)

**Comment by fvgm-spec** [comment]
Authentication succeeds with Airbyte OOS

![Image](https://github.com/airbytehq/PyAirbyte-Hackathon/assets/60470663/7d3ae583-fa3a-4f89-a994-6ea144485a0a)

![Image](https://github.com/airbytehq/PyAirbyte-Hackathon/assets/60470663/b31d5f1a-70db-4b3b-babd-bb4b91d28e8a)

**Comment by fvgm-spec** [comment]
Hi @marcosmarxm @aaronsteers please let me know if you'd need further debugging/research on this issue. Regards.

**Comment by aaronsteers** [comment]
@fvgm-spec - Do I correctly understand (in summary) that auth or config is still not working as expected when run via PyAirbyte? From the error log above, it looks like we might need an `auth_method` key within the `credentials` dictionary expression here: 

![Image](https://github.com/airbytehq/PyAirbyte-Hackathon/assets/18150651/71c27446-c9f5-493a-8872-41f133fe5406)

If you have not already, could you try that and let us know if the source is able to authenticate?

**Comment by aaronsteers** [comment]
From what I can see from the above, other users have probably run into the same challenges in configuring the source with OAuth. It looks like you've tackled the hard part of getting OAuth secrets using localhost redirects. Hoping that the rest is just config nuance. 🤞

**Comment by fvgm-spec** [comment]
Hi @aaronsteers , yes the source is authenticating successfully, please let me know if you need further details:

![Image](https://github.com/airbytehq/PyAirbyte-Hackathon/assets/60470663/a2e85cd1-0350-4c42-8162-668112ac0555)

**Comment by marcosmarxm** [comment]
> Hi @aaronsteers , yes the source is authenticating successfully, please let me know if you need further details:
> 
> ![Image](https://private-user-images.githubusercontent.com/60470663/345424251-a2e85cd1-0350-4c42-8162-668112ac0555.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTc0MzEsIm5iZiI6MTcyMDYxNzEzMSwicGF0aCI6Ii82MDQ3MDY2My8zNDU0MjQyNTEtYTJlODVjZDEtMDM1MC00YzQyLTgxNjItNjY4MTEyYWMwNTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEzMTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NzlkODlmN2FlNzVlYzg5ZTA0MGNiMTgxNzljOGNmOGFkZDMyNGQyYWE4NWVkZDg3MjUyNGJiOWYwZWFiNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1-ncWAl6iUXRGseSeU2dOhj5yxFkiphg-BfxQ42Gx_s)

From this image it doesn't look the source is working with PyAirbyte. Can you check again @fvgm-spec
