### ISSUE TITLE
Debug issues with source-square connector

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte-Hackathon#11]
## Summary

The Square source is having issues when run in PyAirbyte. The goal is to replicate and document any observed issues and then propose a fix.

## Resources to Assist
- PyAirbyte tutorials: https://github.com/airbytehq/quickstarts/tree/main/pyairbyte_notebooks
- PyAirbyte Documentaton: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started 
- PyAirbyte API Reference: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started#api-reference
- Source-linkedin-ads documentation: https://docs.airbyte.com/integrations/sources/linkedin-ads

**Comment by siddhant3030** [comment]
hey can you assign me this issue? I'll look into this

**Comment by marcosmarxm** [comment]
One each time @siddhant3030 📦

**Comment by btkcodedev** [comment]
Can I work on this @marcosmarxm? Raised PR for the [quickstart](https://github.com/airbytehq/PyAirbyte-Hackathon/issues/14)
:)

**Comment by marcosmarxm** [comment]
It is yours @btkcodedev

**Comment by btkcodedev** [comment]
Linking the PR:
https://github.com/airbytehq/airbyte/pull/39377

**Comment by btkcodedev** [comment]
@bindipankhudi, @aaronsteers, @marcosmarxm Pinging about update - PR - https://github.com/airbytehq/airbyte/pull/39377

**Comment by btkcodedev** [comment]
:bow:

**Comment by btkcodedev** [comment]
PR CI tests ran successfully ✅
![Screenshot_20240611-091220~2.jpg](https://github.com/airbytehq/PyAirbyte-Hackathon/assets/47392334/0df11b21-6f60-4bfa-a3bd-502d57c65d20)

**Comment by marcosmarxm** [comment]
@btkcodedev can you try to run a sync using the credentials using PyAirbyte?

**Comment by btkcodedev** [comment]
Yes @marcosmarxm, I've ran with colab and got issues with error handling, 
![image](https://github.com/airbytehq/PyAirbyte-Hackathon/assets/47392334/b0eb5b8a-c883-4487-b260-6590d4992bfd)

**Comment by btkcodedev** [comment]
Solved it with PR https://github.com/airbytehq/airbyte/pull/39377 and CI for that PR is green :smile:

**Comment by btkcodedev** [comment]
Please review https://github.com/airbytehq/airbyte/pull/39377 :bow:

**Comment by bindipankhudi** [comment]
Thank you @btkcodedev. Assigned it to myself for review.

**Comment by bindipankhudi** [comment]
Thank you @marcosmarxm for reviewing! 🙌
