### ISSUE TITLE
End-to-end RAG using Airbyte Cloud, S3 and Pinecone

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte-Hackathon#14]
## Summary
This goal of this task is to show uses how to use `s3` as a data source for their `Pinecone` based vector store, and to implement a short RAG demo based on the loaded data.

## Project Description
This issue broadly involves the following
- Set up a Airbyte cloud connection using the mentioned source and destinations and load some data.
- Perform RAG on data in the mentioned destination. You can choose to do RAG using OpenAI/LangChain, or any other means of your choice.

## Definition of Done
- Deliver documentation (Blog post, Python notebook, etc., ) covering end to end steps including code snippets when applicable. When providing a python notebook, please add a "What / Why / How" blurb at the top to explain what the code is doing.

## Resources to Assist
- Example tutorial: https://github.com/airbytehq/quickstarts/blob/main/vector_store_integration/RAG_using_Snowflake_Cortex.ipynb
- s3 source documentation: https://docs.airbyte.com/integrations/sources/s3
- Pinecone documentation: https://docs.airbyte.com/integrations/destinations/pinecone
- Sample blog post: https://airbyte.com/tutorials/chat-with-your-data-using-openai-pinecone-airbyte-and-langchain

**Comment by btkcodedev** [comment]
Hi @aaronsteers, I've seen some issues have been already assigned :)
I am willing to take up this issue to create a quickstart and write a blog for this
Thanks!!

**Comment by marcosmarxm** [comment]
It is yours btk!

**Comment by bindipankhudi** [comment]
Linking the review - https://github.com/airbytehq/quickstarts/pull/115

**Comment by btkcodedev** [comment]
Any update @bindipankhudi @aaronsteers

**Comment by bindipankhudi** [comment]
Sorry about the delay @btkcodedev. We should review this soon. Thank you for all the great work! :)

**Comment by aaronsteers** [comment]
@btkcodedev - Thanks for your patience. Review posted there in the PR. Only one small set of changes requested, and then I think it's ready to go. (Should not block picking up other tasks.)

**Comment by aaronsteers** [comment]
Approved and merged! Nice work, @btkcodedev !
