### ISSUE TITLE
End-to-end RAG using Airbyte Cloud, S3 and Vectara

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte-Hackathon#15]
## Summary
This goal of this task is to show how Airbyte users can use `s3` as a data source for their `Vectara` vector store destination, and to implement a short RAG demo based on the loaded data.

## Project Description
This issue broadly involves the following
- Set up a Airbyte cloud connection using the mentioned source and destinations. 
- Perform RAG on data in Vectara. You can choose to do RAG using OpenAI/LangChain, or any other means of your choice.

## Definition of Done
- Deliver documentation (Blog post, Python notebook, etc., )covering end to end steps including code snippets when applicable. When providing a python notebook, please add a "What / Why / How" blurb at the top to explain what the code is doing.

## Resources to Assist
- Example tutorial: https://github.com/airbytehq/quickstarts/blob/main/vector_store_integration/RAG_using_Snowflake_Cortex.ipynb
- s3 source documentation: https://docs.airbyte.com/integrations/sources/s3
- Vectara documentation: https://docs.airbyte.com/integrations/destinations/vectara
- Sample blog post: https://airbyte.com/tutorials/chat-with-your-data-using-openai-pinecone-airbyte-and-langchain

**Comment by Chinmay2107** [comment]
Hi @aaronsteers, 
I want to work on this issue. Please assign this to me.

**Comment by marcosmarxm** [comment]
@Chinmay2107 do you need any help?

**Comment by ash-x4** [comment]
Hey @Chinmay2107 are you still working on this? If not ,may I work on this and get it assigned from @marcosmarxm ? Thanks

**Comment by avirajsingh7** [comment]
@marcosmarxm Can you assign me this issue, @Chinmay2107 seems inactive

**Comment by Chinmay2107** [comment]
Hi, I am working on it.

**Comment by avirajsingh7** [comment]
Thanks for confirming @Chinmay2107

**Comment by Suraj-Vishwakarma70** [comment]
Hey @Chinmay2107 I see you have been working on this issue since 3 weeks. 
But I believe this issue doesn't really require that long time to solve! 
If you're stuck some where I am willing to help.
In case you have given up , I am ready to get it assigned.

**Comment by Suraj-Vishwakarma70** [comment]
@marcosmarxm Please assign it to me 🙇

**Comment by Suraj-Vishwakarma70** [comment]
@aaronsteers @bindipankhudi @marcosmarxm Can I get this assigned please?

**Comment by marcosmarxm** [comment]
@Suraj-Vishwakarma70 all yours.

**Comment by ombhardwajj** [comment]
Hey @Suraj-Vishwakarma70,I know you got it assigned very enthusiastically, but do you need some help incase even you are stuck somewhere?

**Comment by Suraj-Vishwakarma70** [comment]
Hello @ombhardwajj 
You are absolutely correct , I was stuck! This isnt as easy as I thought. 
I am planning to give it a last try today.
Would also appreciate if you can help me, I have pinged you.

**Comment by Suraj-Vishwakarma70** [comment]
Thanks for the help @ombhardwajj .
But I am still not able to fix that error and I've decided not invest in more time on this.
You can take this issue and work on it, I will unassign myself.

**Comment by ombhardwajj** [comment]
@aaronsteers Please assign it to me!

**Comment by ombhardwajj** [comment]
The draft of the blog is ready and can be read [here](https://hashnode.com/preview/667fb4edc142ddb1d6899acf)

**Comment by ombhardwajj** [comment]
@aaronsteers I've made a PR and also posted a draft blog.
Please review it!
