### ISSUE TITLE
End-to-end RAG using Airbyte Cloud, S3 and Snowflake Cortex

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte-Hackathon#16]
## Summary
This goal of this task is to show uses how to use `s3` as a data source for their `Snowflake Cortex` based vector store, and to implement a short RAG demo based on the loaded data.

## Project Description
This issue broadly involves the following
- Set up a Airbyte cloud connection using the mentioned source and destinations. 
- Perform RAG on data in Snowflake. You can choose to do RAG using OpenAI/LangChain, or Snowflake's Cortex functions. 

## Definition of Done
- Deliver documentation (Blog post, Python notebook, etc., )covering end to end steps including code snippets when applicable. When providing a python notebook, please add a "What / Why / How" blurb at the top to explain what the code is doing.

## Resources to Assist
- Example tutorial: https://github.com/airbytehq/quickstarts/blob/main/vector_store_integration/RAG_using_Snowflake_Cortex.ipynb
- s3 source documentation: https://docs.airbyte.com/integrations/sources/s3
- Snowflake cortex documentation: https://docs.airbyte.com/integrations/destinations/snowflake-cortex
- Snowflake Cortex functions: https://docs.snowflake.com/en/user-guide/snowflake-cortex/overview
- Sample blog post: https://airbyte.com/blog/build-end-to-end-rag-applications-using-airbyte-and-snowflake-cortex

**Comment by ombhardwajj** [comment]
Please assign it to me, I would like to work upon it!

**Comment by marcosmarxm** [comment]
It is yours!

**Comment by ombhardwajj** [comment]
@marcosmarxm Please unassign me from this as I have not been able to fix it! Someone else can work on it certainly!

**Comment by avirajsingh7** [comment]
@ombhardwajj if you have not started working on this issue, Can I take this one?,
I have already worked on almost similar issue

**Comment by ombhardwajj** [comment]
@avirajsingh7 Alright! Yo can take this!!

**Comment by avirajsingh7** [comment]
@ombhardwajj  thanks,
@bindipankhudi assign me this one also,
I will be raising PR soon

**Comment by bindipankhudi** [comment]
Sounds good! assigned to you @avirajsingh7. Once PR is ready, please add the link for PR here as well. That will be super helpful.

**Comment by avirajsingh7** [comment]
@bindipankhudi here's blog in [docx](https://docs.google.com/document/d/1fYOWLPcRQN2lynAIYBOMlsxfAf_K9TrLq4EXZhSIk6c/edit?usp=sharing) format

**Comment by bindipankhudi** [comment]
@avirajsingh7 blog looks great! We will publish it on Wednesday (PST). Will update here.

**Comment by avirajsingh7** [comment]
Hey @bindipankhudi , any updates on this?

**Comment by bindipankhudi** [comment]
Hi @avirajsingh7 , this has been published! : https://airbyte.com/blog/end-to-end-rag-using-airbyte-cloud-s3-and-snowflake-cortex 
cc @marcosmarxm
