### ISSUE TITLE
End-to-end RAG tutorial using s3, PyAirbyte and Pinecone (using Langchain)

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte-Hackathon#17]
## Summary
The goal is to show users how to use PyAirbyte to load data from `s3` source, store the data in `Pinecone` vector store and perform a short RAG demo (using OpenAI/LangChain) on the loaded data in `Pinecone`.

## Deliverable
Python notebook illustrating end to end RAG using PyAirbyte, `s3` as source & `Pinecone` as destination. Please add a "What / Why / How" blurb at the top of the notebook to explain what the code is doing.

## Resources to Assist
- PyAirbyte tutorials: https://github.com/airbytehq/quickstarts/tree/main/pyairbyte_notebooks
- PyAirbyte Documentaton: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started 
- PyAirbyte API Reference: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started#api-reference
- s3 source documentation: https://docs.airbyte.com/integrations/sources/s3
- LangChain Pinecone support: https://python.langchain.com/v0.1/docs/integrations/vectorstores/pinecone/

**Comment by avirajsingh7** [comment]
@aaronsteers I would like to work on this one

**Comment by marcosmarxm** [comment]
One each time @avirajsingh7

**Comment by topefolorunso** [comment]
Can I take this? @marcosmarxm

**Comment by avirajsingh7** [comment]
@marcosmarxm can you assign me this one, on this issue (https://github.com/airbytehq/PyAirbyte/issues/247#event-13021434114) I was informing about almost same issue

**Comment by avirajsingh7** [comment]
@aaronsteers I have raised the pr, also shared google colab link in pr

**Comment by bindipankhudi** [comment]
@avirajsingh7 The PR have been approved and merged! Great job on the tutorial. Closing this issue. Please feel free to find another issue of interest!
