### ISSUE TITLE
RAG on Snowflake with Airbyte source data

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte-Hackathon#2]
## Summary
Build a RAG solution running on 100% Snowflake-managed infrastructure, using Airbyte.

## Project Description
This broadly involves following steps: 
- Move some data into Snowflake 
- Build a RAG demo in Snowflake, using Snowflake infra and Snowflake Cortex functions. Cortex allows you to vectorize data and perform vector operations like cosine similarity search 

## Deliverable
- Documentation/Readme outlining end to end steps involved in building the RAG solution

## Resources to Assist
- Snowflake Cortex: https://docs.snowflake.com/en/user-guide/snowflake-cortex/overview

**Comment by Harmaton** [comment]
I would love to work on this topic, Thank you :)

**Comment by marcosmarxm** [comment]
Assigned to you!

**Comment by Harmaton** [comment]
@marcosmarxm I have completed my documentation but I am using fake for the embedding model so i cant really get responses, can you provide me with a temporary openai api key just for the purpose of getting the responses in the blog ?

**Comment by Harmaton** [comment]
Here is my [documentation] (https://dev.to/harmaton/how-to-build-rag-on-snowflake-infra-with-airbyte-data-7gp) , waiting for the api key to finalize. Thank you!

**Comment by marcosmarxm** [comment]
Thanks @Harmaton let wait for Bindi to check the API keys.

**Comment by bindipankhudi** [comment]
@Harmaton were you able to get a key from @marcosmarxm?

**Comment by Harmaton** [comment]
No not yet @bindipankhudi . However, I have completed the blog waitimg for review. :)

**Comment by bindipankhudi** [comment]
sent you a key in DM, @Harmaton. I will look at the blog post.

**Comment by bindipankhudi** [comment]
@Harmaton - actually for this issue, you can keep using fake embedding and vectorize data using Cortex function, so basically overwrite the embedding column in the snowflake using cortex'x embed function.

**Comment by bindipankhudi** [comment]
also, @Harmaton when it's complete, if you could share the blog in a google doc that would be great! :)

**Comment by Harmaton** [comment]
Okay, noted. Is it good practice to use vector embedding on data I passed to snowflake cortex directly (where I have to embed uaing fake or openai?)?

**Comment by Harmaton** [comment]
Okay, noted. Is it good practice to use vector embedding on data I passed to snowflake cortex directly (where I have to embed uaing fake or openai?)? Or should I use either?

**Comment by Harmaton** [comment]
[Final Submission](https://docs.google.com/document/d/1EvvDd_V4p3BHZ_XjJ7FPSEKFlOje6B_WQ5gLPhtGRTw/edit?usp=sharing) @bindipankhudi

**Comment by marcosmarxm** [comment]
Thanks @Harmaton I'll Bindi to take a look!

**Comment by bindipankhudi** [comment]
Thank you @Harmaton. The blog post looks good! Thank you for making the updates. Could you share a picture and a quick bio for publishing on our side? Thank you! :)

**Comment by Harmaton** [comment]
[BIO + IMAGE -> HARMATON](https://docs.google.com/document/d/1d8Drdhd4VhGSHTS4dbYGtsTF05HO52KnD2b1Wtuz3iQ/edit)
