### ISSUE TITLE
End-to-end RAG tutorial using source facebook marketing, PyAirbyte and Zilliz (using Langchain)

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte-Hackathon#20]
## Summary
The goal is to show users how to use PyAirbyte to load data from `Facebook marketing`  source, store the data in `Zilliz` vector store and perform a short RAG demo (using OpenAI/LangChain) on the loaded data in `Zilliz`. 

## Deliverable
Python notebook illustrating end to end RAG using PyAirbyte, `Facebook marketing` as source & `Zilliz` as destination. Please add a "What / Why / How" blurb at the top of the notebook to explain what the code is doing.

## Resources to Assist
- PyAirbyte tutorials: https://github.com/airbytehq/quickstarts/tree/main/pyairbyte_notebooks
- PyAirbyte Documentaton: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started 
- PyAirbyte API Reference: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started#api-reference
- Facebook marketing source documentation: https://docs.airbyte.com/integrations/sources/facebook-marketing
-  Milvus (Zilliz) langchain integration: https://python.langchain.com/v0.1/docs/integrations/vectorstores/zilliz/

**Comment by arjun-prabhakar-123** [comment]
Hello @aaronsteers,

I'm interested in working on this issue. Could you please assign it to me?

Thanks!

**Comment by marcosmarxm** [comment]
It is yours!

**Comment by marcosmarxm** [comment]
@arjun-prabhakar-123 do you need any help ehre?

**Comment by ombhardwajj** [comment]
@marcosmarxm Can I get this assigned? @arjun-prabhakar-123 seems to be inactive!

**Comment by ombhardwajj** [comment]
@marcosmarxm @bindipankhudi Can I work on this please!?

**Comment by marcosmarxm** [comment]
@ombhardwajj let's wait until Monday, if they don't reply it is yours!

**Comment by ombhardwajj** [comment]
@marcosmarxm  They have not replied!! Its mine :)

**Comment by gemsteam** [comment]
Hi @marcosmarxm, Can i work on this issue, I am new to airbyte :)

**Comment by ombhardwajj** [comment]
@gemsteam sorry but I had already planned to work upon it!
@marcosmarxm @bindipankhudi Please assign it to me!

**Comment by marcosmarxm** [comment]
@arjun-prabhakar-123 unassigned, @ombhardwajj assigned. sorry @gemsteam but issues are assigned in other of requests.

**Comment by marcosmarxm** [comment]
@ombhardwajj sorry I'd jsut you have already assigned issues. I'll give this one to @gemsteam

**Comment by ombhardwajj** [comment]
@marcosmarxm #30 aand #31 were part of Feature Contributions (if I am not wrong) and they will still be. Wheras this issue is for quickstarts and tutorials. I could have been assigned this isnt it?

**Comment by ombhardwajj** [comment]
@marcosmarxm Could you please confirm if the issues I mentioned are part of Feature Contributions?🙇

**Comment by btkcodedev** [comment]
@gemsteam If this issue is too complex, can I work on this? 🙂

**Comment by ombhardwajj** [comment]
@btkcodedev I just wanted to remind you that I had expressed interest in this issue initially. 🙇 
If @gemsteam finds it challenging and is open to passing it on, I would appreciate it if I could be considered next in line.
Hope you understand 😄

**Comment by btkcodedev** [comment]
You have already #30 and #31 to work on isn't it

**Comment by ombhardwajj** [comment]
@btkcodedev According to the rules we can get a quickstart as well as Feature issue assigned at the same time isn't it?
Most prolly they are Feature issues , but lets wait for the confirmation!

**Comment by btkcodedev** [comment]
One issue at a time regardless of category and you already have 2 issues, my dear friend
Cc: @marcosmarxm

**Comment by Harmaton** [comment]
I can work on it as well if you dont @marcosmarxm incase my friends here are assigned other tasks

**Comment by gemsteam** [comment]
Hi @btkcodedev, Yes you can take this up my friend :)

**Comment by btkcodedev** [comment]
Cool! Thanks! Also I can see other volunteers are assigned with other issues.
Cc: @marcosmarxm I am willing to take this up❤️

**Comment by ombhardwajj** [comment]
@marcosmarxm Can you please clarify if we can work on a feature and a quickstart at the same time?

**Comment by btkcodedev** [comment]
@ombhardwajj For your reference, Please go through the first point in https://airbyte.com/community/content-hackathon
Thanks
Ref: 
![image](https://github.com/airbytehq/PyAirbyte-Hackathon/assets/47392334/3dc2b63d-2f98-4d1b-9977-ba4bb162bce5)

**Comment by ombhardwajj** [comment]
Looking at the rules
We cannot be assigned "several" features "and" tutorials at the same time.
But we can be assigned a single feature "and" tutorial at the same time . 
Notice "and" but not "or"
Thanks
@btkcodedev 
Cc: @marcosmarxm

**Comment by btkcodedev** [comment]
Bruh🙄
@marcosmarxm Please look at this

**Comment by btkcodedev** [comment]
Linking PR
https://github.com/airbytehq/quickstarts/pull/126

**Comment by bindipankhudi** [comment]
Thank you @btkcodedev, Approved & merged!
