### ISSUE TITLE
End-to-end RAG tutorial using Amazon SQS, PyAirbyte and Milvus (using Langchain)

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte-Hackathon#21]
## Summary
The goal is to show users how to use PyAirbyte to load data from `Amazon SQS` source, store the data in `Milvus` and perform a short RAG demo (using OpenAI/LangChain) on the loaded data in `Milvus`. 

## Deliverable
Python notebook illustrating end to end RAG using `PyAirbyte`, `Amazon SQS` source,`LangChain` & `Milvus`. Please add a "What / Why / How" blurb at the top of the notebook to explain what the code is doing.

## Resources to Assist
- PyAirbyte tutorials: https://github.com/airbytehq/quickstarts/tree/main/pyairbyte_notebooks
- PyAirbyte Documentaton: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started 
- PyAirbyte API Reference: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started#api-reference
- Amazon SQS documentation: https://docs.airbyte.com/integrations/sources/amazon-sqs
- Milvus (Zilliz) langchain integration: https://python.langchain.com/v0.1/docs/integrations/vectorstores/zilliz/

**Comment by aazam-gh** [comment]
I'll take this up :)

**Comment by marcosmarxm** [comment]
Milvus, probably a typo from other issue.

**Comment by marcosmarxm** [comment]
@aaronsteers fyi

**Comment by marcosmarxm** [comment]
@aazam-gh are you working on this one? Need any help?

**Comment by aaronsteers** [comment]
@aazam-gh - Yes, @marcosmarxm is correct: this should be "Milvus". Typo retained from copy-paste during task creation. I've updated the description.

**Comment by 15vaibhav2003** [comment]
Hey, Just in case @aazam-gh is no more working on this or planning to quit, I am quite eager to work on this!
Please assign it to me if thats the case!

**Comment by aazam-gh** [comment]
Hi, I won't have time to work on this, you can unassign me :)

**Comment by 15vaibhav2003** [comment]
@aazam-gh Thanks for the quick reply!
@marcosmarxm  Please assign it to me!

**Comment by 15vaibhav2003** [comment]
@aaronsteers Before this issue is resolved another issue needs to your attention. The Amazon SQS source connector must be updated to remove the legacy Logger , as told by @marcosmarxm on Slack. Therefore I request you to create a new issue for this task in this hackathon and assign it to me!

**Comment by 15vaibhav2003** [comment]
Hey Team @marcosmarxm @aaronsteers @bindipankhudi any update on this?

**Comment by marcosmarxm** [comment]
@15vaibhav2003 I created https://github.com/orgs/airbytehq/projects/75/views/3?pane=issue&itemId=68752114 please comment in the isssue so I can assigned to you.

**Comment by bleonard** [comment]
@15vaibhav2003 It looks like things didn't work out. Thanks for trying.
