### ISSUE TITLE
Sentiment analysis using Airbyte Cloud, Google sheets, and Snowflake Cortex

### ISSUE THREAD

**Issue by bindipankhudi** [airbytehq/PyAirbyte-Hackathon#23]
## Summary
This goal of this task is to show users how they load some dummy user review data from google sheets into`Snowflake Cortex` based vector store, and perform sentiment analysis using [Snowflake Cortex's sentiment function](https://docs.snowflake.com/en/sql-reference/functions/sentiment-snowflake-cortex). 

## Project Description
This issue broadly involves the following
- Set up a Airbyte cloud connection using the mentioned source and destinations. (Feel free to use dummy reviews data like restaurant, or product reviews) 
- Do sentiment analysis on data in Snowflake. 

## Definition of Done
- Deliver documentation (Blog post, Python notebook, etc., )covering end to end steps including code snippets when applicable. When providing a python notebook, please add a "What / Why / How" blurb at the top to explain what the code is doing.

## Resources to Assist
- Example tutorial: https://github.com/airbytehq/quickstarts/blob/main/vector_store_integration/RAG_using_Snowflake_Cortex.ipynb
- Google sheets documentation: https://docs.airbyte.com/integrations/sources/google-sheets
- Snowflake cortex documentation: https://docs.airbyte.com/integrations/destinations/snowflake-cortex
- Snowflake Cortex functions: https://docs.snowflake.com/en/user-guide/snowflake-cortex/overview
- Sample blog post: https://airbyte.com/blog/build-end-to-end-rag-applications-using-airbyte-and-snowflake-cortex

**Comment by bala-ceg** [comment]
Hi @aaronsteers, Can i work on this issue, while the issue #13 is sorted out?

**Comment by marcosmarxm** [comment]
It is yours @bala-ceg

**Comment by bala-ceg** [comment]
Hi @bindipankhudi, 
Can you please confirm whether the Jupyter notebook tutorial like [this](https://github.com/airbytehq/quickstarts/blob/main/vector_store_integration/RAG_using_Snowflake_Cortex.ipynb) is sufficient for this issue

**Comment by bindipankhudi** [comment]
Hi @bala-ceg, yep, what you shares is sufficient. Please make sure to add enough description in the notebook, so it's self-sufficient and easy to follow.

**Comment by bala-ceg** [comment]
@bindipankhud fyi, requested credentials in dm.

**Comment by bala-ceg** [comment]
Hi @bindipankhudi,
Does this issue requires use of snowflake (not snowflake cortex) to run batch predictions?

**Comment by bala-ceg** [comment]
This is initial  google colab notebook draft for sentiment analysis using snowflake
https://colab.research.google.com/drive/1fwCL2dvCGAsO9SZQ_wWEEVVDjzmGfc0u?usp=sharing

**Comment by bindipankhudi** [comment]
Thank you @bala-ceg!  we will review it soon.

**Comment by bala-ceg** [comment]
Thanks @bindipankhudi , looking forward to hear from you.

**Comment by bindipankhudi** [comment]
Hi @bala-ceg, couple of comments: 
1. Before you create a PR, please add some comments on what is being done in the notebook.
2. Please use Cortex's sentiment analysis function to do the analysis: https://docs.snowflake.com/en/sql-reference/functions/sentiment-snowflake-cortex. You are using openAI here.

**Comment by bala-ceg** [comment]
Hi @bindipankhudi,
I am getting the below error, is there anything do i need to configure from snowflake?
```
ProgrammingError: 002141 (42601): SQL compilation error:
Unknown user-defined function SNOWFLAKE.CORTEX.COMPLETE
```
https://colab.research.google.com/drive/1fwCL2dvCGAsO9SZQ_wWEEVVDjzmGfc0u?usp=sharing

**Comment by bindipankhudi** [comment]
@bala-ceg you can check in snowflake to see if you have access to the complete function. Here is a screenshot from one of our snowflake accounts. 
<img width="659" alt="Screenshot 2024-06-25 at 11 56 35 AM" src="https://github.com/airbytehq/PyAirbyte-Hackathon/assets/158614730/fa157d4f-ba67-48b3-8af3-0c9adda2df0f">

**Comment by bala-ceg** [comment]
Hi @bindipankhudi,
I am not able to enable cortex in my snowflake account. is it possible to provide me demo/sample credentials that airbyte team has?

**Comment by bindipankhudi** [comment]
HI @bala-ceg, let me check with @marcosmarxm if this is something we can share.

**Comment by bala-ceg** [comment]
Thanks @bindipankhudi, I am waiting for this. I will close this by today or tomorrow

**Comment by bindipankhudi** [comment]
Hi @bala-ceg, I checked with Marcos and we decided that it's not ideal for us to share our database credentials, so seems like the most plausible option for you might be to drop this ticket and pick an new one.

**Comment by ombhardwajj** [comment]
Just incase the issue I suggested is not being added, and if @bala-ceg is dropping off ,I would like to give this a try so please assign me! @marcosmarxm  @bindipankhudi

**Comment by ombhardwajj** [comment]
Hey @bala-ceg Please confirm if you've dropped off!

**Comment by bala-ceg** [comment]
Hi @ombhardwajj, @marcosmarxm  & @bindipankhudi ,
let me take another run at getting cortex support to my account. If not i will unassign muself

**Comment by bala-ceg** [comment]
I am able to get cortex support, will create a pr within next 24 hrs

**Comment by aaronsteers** [comment]
Thanks, @bala-ceg. I'll check in tomorrow (Saturday) in case there's any assistance I can lend or questions I can answer.

**Comment by avirajsingh7** [comment]
@bala-ceg If you are still stuck with this issue, I would like to work on this. (Already Raised Pr for all other issues assigned to me)
cc: @aaronsteers, @marcosmarxm

**Comment by bala-ceg** [comment]
Thanks for chiming in on this issue, but i got it for now

**Comment by bala-ceg** [comment]
this is the draft collab notebook - https://colab.research.google.com/drive/1fwCL2dvCGAsO9SZQ_wWEEVVDjzmGfc0u?usp=sharing

**Comment by bala-ceg** [comment]
@bindipankhudi can you please review the PR?

**Comment by bleonard** [comment]
Merged https://github.com/airbytehq/quickstarts/pull/129
