### ISSUE TITLE
Summarize scraped customer reviews from amazon product page using Apify & Snowflake Cortex

### ISSUE THREAD

**Issue by bindipankhudi** [airbytehq/PyAirbyte-Hackathon#24]
## Summary
This goal of this task is to show users how they load scraped customer reviews data from Amazon into`Snowflake Cortex` based vector store, and perform summarization using [Snowflake Cortex's summarize function](https://docs.snowflake.com/en/sql-reference/functions/summarize-snowflake-cortex). 

## Project Description
This issue broadly involves the following
- Pick a product page from Amazon
- Use Apify to scrape top 50-100 product reviews. You might need to do some customization to extract review data only.
- Set up Apify source and Snowflake Cortex destination in Airbyte Cloud. You should be able to specify the scraped dataset in Apify source.
- Perform summarization of data in Snowflake Cortex. The summary should comprise key points and overall customer sentiment for the product. 

## Definition of Done
- Deliver documentation (Blog post, Python notebook, etc., )covering end to end steps including code snippets when applicable. When providing a python notebook, please add a "What / Why / How" blurb at the top to explain what the code is doing.

## Resources to Assist
- Apify: https://apify.com/
- Example tutorial: https://github.com/airbytehq/quickstarts/blob/main/vector_store_integration/RAG_using_Snowflake_Cortex.ipynb
- Snowflake cortex documentation: https://docs.airbyte.com/integrations/destinations/snowflake-cortex
- Snowflake Cortex functions: https://docs.snowflake.com/en/user-guide/snowflake-cortex/overview
- Sample blog post: https://airbyte.com/blog/build-end-to-end-rag-applications-using-airbyte-and-snowflake-cortex

**Comment by gupta-arpan** [comment]
Hi @bindipankhudi i would like to work on this issue can you please assign me this ?

**Comment by bindipankhudi** [comment]
Hi @gupta-arpan, assigned to you! Let us know if you have any questions getting started!

**Comment by gupta-arpan** [comment]
Hi @bindipankhudi Sry but for this week I can’t continue, If anyone wants to continue they can on this issue. Thanks

**Comment by avirajsingh7** [comment]
@bindipankhudi can you assign me this issue?

**Comment by bindipankhudi** [comment]
It's assigned to you now @avirajsingh7!

**Comment by avirajsingh7** [comment]
@bindipankhudi should I perform Rag then query to summarize the data like done in this [blog](https://airbyte.com/blog/build-end-to-end-rag-applications-using-airbyte-and-snowflake-cortex)? or is there any specific method we can use?
we have data in vector form.

I have written half blog , [here](https://aviraj-writes.hashnode.dev/preview/64d50274876774000fa747b9)

**Comment by bindipankhudi** [comment]
Hi @avirajsingh7, in the blog we use the Cortex`complete` function. For your blog, we should use the `summarize` function: https://docs.snowflake.com/en/user-guide/snowflake-cortex/llm-functions#label-cortex-llm-summarize. If you think `summarize` is not working well, you could use `complete` which does general QnA and might be more flexible.

**Comment by avirajsingh7** [comment]
@bindipankhudi I am thinking of using complete function which will give more flexibility to user and I can provide the link to google colab which will reduce my workload also ( creating different notebook will be whole new task).

also summarize function takes only text as [arguments](https://docs.snowflake.com/en/sql-reference/functions/summarize-snowflake-cortex)

**Comment by avirajsingh7** [comment]
@bindipankhudi 
Completed the blog for this issue, [here](https://aviraj-writes.hashnode.dev/preview/64d50274876774000fa747b9),
Once  aribyte_team  approve I will publish this on hashnode.

**Comment by bindipankhudi** [comment]
Hi @avirajsingh7 blog is looking great! Just one request - Could you add the response you got from LLM towards the end as well. Thank you! Once that is in, lmk and i can quickly approve for publish.

**Comment by bindipankhudi** [comment]
@avirajsingh7 could you also share a quick bio for yourself for publishing on Airbyte's blogs.

**Comment by avirajsingh7** [comment]
@bindipankhudi I used fake for embeddings in snowflake, because OpenAi Api key was reaching rate limits ( using trial version).

Here's my bio : 

Aviraj Gour is a final-year B.Tech student in Mathematics and Computing at the National Institute of Technology, Hamirpur. He interned at Tech4Dev, where he created source connectors and improved workflows. Aviraj has proved his skills by contributing to open-source projects and winning two Airbyte hackathons back to back.

Linkdin : https://www.linkedin.com/in/aviraj-gour-850765232/
Image : https://drive.google.com/file/d/1X9n9JFrEAvLk1vywMyCIt5f55khUWQ4x/view?usp=drivesdk

**Comment by bindipankhudi** [comment]
got it! No worries! I am closing this ticket. (If you are doing another OpenAI related task, DM me on slack and I can share a temporary OpenAI key with you) Thank you for sharing your details for the blog post. Please wait for us to publish on Airbyte blogs before you publish on your site. We should publish early next week and I will msg you once it is posted. Thank you!

**Comment by bindipankhudi** [comment]
Hey @avirajsingh7 one more thing, can you share the content in a google doc. :) will make it easy for us with the pictures and all. thank you :)

**Comment by avirajsingh7** [comment]
@bindipankhudi here docs [link](https://docs.google.com/document/d/1jmkSnFuclFUo18FiRb41LHB8flwksE3IGdEI-r6sXPM/edit?usp=sharing)

**Comment by bindipankhudi** [comment]
Hi @avirajsingh7, your blog has been published! - https://airbyte.com/blog/streamlining-amazon-product-review-analysis-with-apify-and-snowflake-cortex 🚀 . It's also featured on the right on our [blogs page](url). Will appreciate if you could wait a week before publishing on your website due to SEO optimization reasons on our end. cc @marcosmarxm
