### ISSUE TITLE
RAG based recommendation system using PyAibyte and Shopify data

### ISSUE THREAD

**Issue by bindipankhudi** [airbytehq/PyAirbyte-Hackathon#25]
## Summary
The goal is to show users how to use PyAirbyte to load product from `Shopify` source, store the data in `Pinecone` (or any other vector store of your choice) and write a simple recommendation system based on similarity search. 

## This issue broadly involves doing the following: 
- Set up a Shopify account (load it with dummy data)
- Load specific streams (products, etc) from Shopify source using PyAirbyte library. Pick streams based on traits which might make for a good recommendation system. 
- Create documents out of relevant fields (from the loaded streams) and store them a vector store (see GenAI tutorial for example)
- Create a prompt for suggesting recommendations given a specific product 

## Deliverable
Python notebook illustrating the recommendation system. Please add a "What / Why / How" blurb at the top of the notebook to explain what the code is doing.

## Resources to Assist
- Shopify tutorial: https://github.com/airbytehq/quickstarts/blob/main/pyairbyte_notebooks/PyAirbyte_Shopify_Demo.ipynb
- PyAirbyte GenAI tutorial: https://github.com/airbytehq/quickstarts/blob/main/pyairbyte_notebooks/PyAirbyte_Document_Creation_RAG_with_Langchain_Demo.ipynb
- PyAirbyte Documentaton: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started 
- PyAirbyte API Reference: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started#api-reference

**Comment by vishal2376** [comment]
I want to work on this issue. Can you assign it to me

**Comment by bindipankhudi** [comment]
Hi @vishal2376, assigned to you! Let us know if you have questions getting started.

**Comment by avirajsingh7** [comment]
@vishal2376  if you have not started working on this issue, Can I take this one?,
I have already worked on almost similar issue

**Comment by vishal2376** [comment]
Not done yet, seems difficult for me to complete it

@avirajsingh7 you can work on it

**Comment by avirajsingh7** [comment]
@vishal2376 let me know if you want to work on other issue and need help

@bindipankhudi can you assign me this issue, I will be raising PR soon

**Comment by marcosmarxm** [comment]
@avirajsingh7 only work on issues you have been assigned.

**Comment by avirajsingh7** [comment]
sure 👍  @marcosmarxm

**Comment by bindipankhudi** [comment]
Linking PR - https://github.com/airbytehq/quickstarts/pull/116

**Comment by bleonard** [comment]
Linking the PR https://github.com/airbytehq/quickstarts/pull/118
