### ISSUE TITLE
Debug issues with source-linkedin-ads connector

### ISSUE THREAD

**Issue by bindipankhudi** [airbytehq/PyAirbyte-Hackathon#26]
The Airtable source is having issues when run in PyAirbyte. The goal is to replicate and document any observed issues and then propose a fix.

## Resources to Assist
- PyAirbyte tutorials: https://github.com/airbytehq/quickstarts/tree/main/pyairbyte_notebooks
- PyAirbyte Documentaton: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started 
- PyAirbyte API Reference: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started#api-reference
- Source-linkedin-ads documentation: https://docs.airbyte.com/integrations/sources/linkedin-ads

**Comment by btkcodedev** [comment]
I would like to take this issue @marcosmarxm, Raised PR for Source-Square

**Comment by btkcodedev** [comment]
Also need creds here, Please ping @btkcodedev in slack CC: @bindipankhudi :bow:

**Comment by marcosmarxm** [comment]
@btkcodedev can you ping me on slack?

**Comment by btkcodedev** [comment]
There are no main issues with the present connector when syncing with pyairbyte
Ref:
![image](https://github.com/airbytehq/PyAirbyte-Hackathon/assets/47392334/af0b8d8f-75d2-4494-888a-be730b65177b)

However, there is a small nits in readme commands, schemas as the source selector is from "elements":{} from the response
I've raised a PR for that: https://github.com/airbytehq/airbyte/pull/39442
Please review :bow:

**Comment by btkcodedev** [comment]
Linking PR: https://github.com/airbytehq/airbyte/pull/39442
CC: @bindipankhudi @marcosmarxm :bowing_man: 
Thanks!!
