### ISSUE TITLE
Illustrate the usage of `langchain_airbyte` package

### ISSUE THREAD

**Issue by bindipankhudi** [airbytehq/PyAirbyte-Hackathon#27]
## Summary
The goal is to show how LangChain users can load data from Airbyte sources (such as Github) using `langchain_airbyte` package, store the data into a vector database, and perform a basic QnA on that data. 

## Description
This tasks involves the following steps:
- Use `langchain-airbyte` package to load data from a specific Airbyte source. This package will load data into documents. 
- Store the documents in a vector db of your choice 
- Perform a QnA on stored data

## Deliverables 
Python notebook illustrating the end to end process above. Please add a "What / Why / How" blurb at the top of the notebook to explain what the code is doing.

## Resources  
- `LangChain-Airbyte` package usage: https://python.langchain.com/v0.2/docs/integrations/document_loaders/airbyte/
- PyAirbyte tutorials: https://github.com/airbytehq/quickstarts/tree/main/pyairbyte_notebooks (includes GenAI example)
- PyAirbyte Documentaton: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started 
- PyAirbyte API Reference: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started#api-reference

**Comment by rifaqat-ali** [comment]
Hey, Team Airbyte!
Please assign it to me . I am eager to work on this!

**Comment by marcosmarxm** [comment]
It is yours @rifaqat-ali

**Comment by ombhardwajj** [comment]
@rifaqat-ali  are you still working on it?

**Comment by rifaqat-ali** [comment]
@ombhardwajj I've been working on it . Currently stuck somewhere in the middle. Will let you know if I plan to give up!

**Comment by rifaqat-ali** [comment]
I've been bombarded with a lot of work in office. So I wont be able to work on it.
@ombhardwajj you can get it assigned if you wish.

**Comment by ombhardwajj** [comment]
@marcosmarxm Please assign it to me , I would like to work on this!

**Comment by marcosmarxm** [comment]
@ombhardwajj done

**Comment by ombhardwajj** [comment]
Please review airbytehq/quickstarts#119

**Comment by bindipankhudi** [comment]
@ombhardwajj added a comment to PR.

**Comment by ombhardwajj** [comment]
@bindipankhudi Please review the updated PR! airbytehq/quickstarts#119

**Comment by bindipankhudi** [comment]
Hi @ombhardwajj, Thank you for updating the PR. Reviewed and merged! 🥳
