### ISSUE TITLE
End to End RAG with Airbyte, Jira  and Pinecone

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/PyAirbyte-Hackathon#29]
Summary
This goal of this task is to show uses how to use Jira as a data source for their Pinecone-based vector store, and to implement a short RAG demo based on the loaded data.
Project Description
This issue broadly involves the following
Set up a Airbyte cloud connection using the mentioned source and destinations, and move some data (Option to use PyAirbyte)
Perform RAG on data in the mentioned destination. You can choose to do RAG using OpenAI/LangChain, or any other means of your choice.
Definition of Done
Deliver documentation (Blog post, Python notebook, etc.) covering end to end steps including code snippets when applicable. When providing a python notebook, please add a “What / Why / How” blurb at the top to explain what the code is doing.
Use Case
We can use this to search a particular Jira if it exists in the Jira Project
Ask to summarize the particular Jira Issue
Filter the jira issues based on the priority /severity

**Comment by bala-ceg** [comment]
Hi @marcosmarxm , 
Can you please assign this issue to me?

**Comment by btkcodedev** [comment]
Hi, I would like to work on this issue if possible, @bala-ceg as you are already assigned to https://github.com/airbytehq/PyAirbyte-Hackathon/issues/23, if you don't have any problem.
CC: @marcosmarxm  :bow:

**Comment by bala-ceg** [comment]
Hi @btkcodedev, 
issue #23 ,that was in review

**Comment by marcosmarxm** [comment]
@btkcodedev this issue was suggested by Balaji :D

**Comment by bala-ceg** [comment]
[PR#123](https://github.com/airbytehq/quickstarts/pull/123) has been created for this issue

**Comment by bindipankhudi** [comment]
Thank you @bala-ceg! I will take a look shortly.

**Comment by bindipankhudi** [comment]
Reviewed and merged! Thank you @bala-ceg for sharing a google colab as well! :)
