### ISSUE TITLE
Add Parallel processing for Pinecone destination

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte-Hackathon#3]

**Comment by ombhardwajj** [comment]
@aaronsteers Please add some description for this project and link some useful resources!

**Comment by aaronsteers** [comment]
@ombhardwajj - Thank you for your interest. Upon further research we have found that this may not be possible without some significant upstream changes in the CDK. I am closing this issue and I apologize for the confusion. We do have a couple more unclaimed issues (I think just 2 as of now) and we expect to have a few more opened up by end of day if you would like to check back then. Thanks again!
