### ISSUE TITLE
Quickstart for End to End RAG using Gitlab, PyAirbyte, and Qdrant

### ISSUE THREAD

**Issue by bindipankhudi** [airbytehq/PyAirbyte-Hackathon#35]

**Comment by avirajsingh7** [comment]
@bindipankhudi this one was suggested by me, Can i work on this one?

**Comment by bindipankhudi** [comment]
Yes @avirajsingh7 go for it!

**Comment by avirajsingh7** [comment]
@bindipankhudi I have created a pr for this issue.

**Comment by bindipankhudi** [comment]
Thank you @avirajsingh7. Take a look now.
