### ISSUE TITLE
Fix Source Connector AmazonSQS

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/PyAirbyte-Hackathon#36]
It looks the current connector is broken and need to fix in the main repo.
Necessary to finish https://github.com/orgs/airbytehq/projects/75/views/3?pane=issue&itemId=63202738.

DoD = Submit PR in Airbyte repository fixing the existing connector.

**Comment by btkcodedev** [comment]
Linking Bulk PR: https://github.com/airbytehq/airbyte/pull/40215 that will fix this issue

**Comment by 15vaibhav2003** [comment]
@marcosmarxm Incase the PR mentioned by @btkcodedev isn't merge ready yet, you can assign it to me 🙇

**Comment by 15vaibhav2003** [comment]
@marcosmarxm Do you have any update regarding how long it will take to get that PR merged? 
In case its gonna take a lot of time, can I just get this specific thing fixed 🙏

**Comment by btkcodedev** [comment]
Update: Seems like the break is not related to Logger alone, it has been separated from the bulk update. 
Ref: https://github.com/airbytehq/airbyte/pull/40215#issuecomment-2194089752

As connector is failing in the master, please continue the fixing if possible

**Comment by 15vaibhav2003** [comment]
@btkcodedev I see you are working on it [here](https://github.com/airbytehq/airbyte/pull/40582)
Can you give some idea how long it will take?

**Comment by btkcodedev** [comment]
The connector seems to have dependency issues while migrating to poetry, along with logger, and is failing its CI. it is yet to be discussed,

You can try to make the CI green with another PR, if possible

**Comment by btkcodedev** [comment]
@15vaibhav2003, That PR is not for this hackathon, The connector is being migrating to poetry, along with logger, and is failing its CI due to dependency issues. it is yet to be discussed,

You can try to make the CI green with another PR, if possible

**Comment by itsxdamdam** [comment]
@aaronsteers can i get assigned to this

**Comment by marcosmarxm** [comment]
this issue was created to help @15vaibhav2003 finish his other task.
