### ISSUE TITLE
Create new PGVector Airbyte destination

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte-Hackathon#5]
## Summary

Modeling after the Snowflake Cortex destination, this new connector would support loading to Postgres "PGVector" as a local vector store native to Postgres.

**Comment by Hashcode-Ankit** [comment]
@aaronsteers  this is my second choice 
first one is this one: https://github.com/airbytehq/PyAirbyte-Hackathon/issues/6

**Comment by marcosmarxm** [comment]
@Hashcode-Ankit I assigned another issue to you.

**Comment by bala-ceg** [comment]
Hi Aaron,Marcos
Ideally to develop this Vector DB destination, is there any samples that i can refer?

**Comment by marcosmarxm** [comment]
@aaronsteers do you have any resources?

**Comment by aaronsteers** [comment]
Hi, @bala-ceg . The best resource right now would be to start with a copy of the new Snowflake Cortex destination. That can be found in the `airbytehq/airbyte` repo under `airbyte-integrations/connectors/destination-snowflake-cortex`.

This destination combines helpers from PyAirbite as well as from the vector store CDK, and is probably the best place to start.

Basic Postgres functionally can be relied upon from the PosgresSqlProcessor class in PyAirbyte, similar to how that destination builds on the Snowflake processor. 

Hope this helps!!

**Comment by fvgm-spec** [comment]
Hi @marcosmarxm could you please assign this one to me?

**Comment by aaronsteers** [comment]
@fvgm-spec - It's yours! 🙏 Let us know if you have any questions!

**Comment by fvgm-spec** [comment]
Hi @aaronsteers , could you please unassign me this issue? As I didn't have enough time to work on it. Thanks!

**Comment by aaronsteers** [comment]
Shipped by @aldogonzalez8 last week! 🚀 🙌 

Very excited to see this launched.

Closing this hackathon issue now that the connector is live.
