### ISSUE TITLE
Builder: Adding a custom source to PyAirbyte using the no-code builder

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte-Hackathon#7]
## Summary

This blog post would focus on how to build a custom connector manifest using the Low-Code builder and then executing that connector from PyAirbyte.

## Definition of Done

Blog post illustrating how to build custom connectors and then executing them from PyAirbyte.

## Resources to Assist

- PyAirbyte tutorials: https://github.com/airbytehq/quickstarts/tree/main/pyairbyte_notebooks
- PyAirbyte Documentaton: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started
- PyAirbyte API Reference: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started#api-reference
- Sample blog post: https://airbyte.com/blog/manage-and-orchestrate-airbyte-connections-using-python

New feature PR (WIP) to further streamline this:

- https://github.com/airbytehq/PyAirbyte/pull/175

**Comment by fvgm-spec** [comment]
Hi @aaronsteers , I am interested on participating writing this piece, I have recently written a [tutorial](https://airbyte.com/blog/migrating-your-elt-data-pipeline-to-pyairbyte) in Airbyte blog.

**Comment by aaronsteers** [comment]
> Hi @aaronsteers , I am interested on participating writing this piece, I have recently written a [tutorial](https://airbyte.com/blog/migrating-your-elt-data-pipeline-to-pyairbyte) in Airbyte blog. 

Great! Assigning you to this issue. 👍

Let us know if you have any questions or issues!

**Comment by fvgm-spec** [comment]
Hi @aaronsteers, do you agree with @avirajsingh7? is it worth writing two tutorials on the same topic?

**Comment by bindipankhudi** [comment]
Good point. let's wait for @aaronsteers for feedback here.

**Comment by aaronsteers** [comment]
Hi, @fvgm-spec. Apologies for the confusion. This particular item was to focus on no-code connectors, which can be represented and "installed" by copying yaml files.

The related item:

- https://github.com/airbytehq/PyAirbyte/issues/247

was intended to focus on custom Python connectors, which require a pip install.

I think both make sense - and I've update the related item to more clearly focus on the nature of Python connectors specifically.

**Comment by fvgm-spec** [comment]
Hi @aaronsteers thanks for both updates, I will be catching the post on building no-code connectors maybe tomorrow, and I will take a look into the PR.

Regards.

**Comment by aaronsteers** [comment]
@fvgm-spec #175 has shipped! 

The fresh-out-of-the-oven `v0.12.0` release of PyAirbyte includes a new `source_manifest` argument in the experimental `get_source()` implementation (which also includes a Docker executor).

API Docs here: https://airbytehq.github.io/PyAirbyte/airbyte/experimental.html#get_source

And PR that shipped this feature is here:

- #175

Please let us know if you have questions or if you run into any issues.

**Comment by aaronsteers** [comment]
In case it is helpful, I wanted to share this Loom demo video that I recorded this morning. The link to my code is in the video description.

https://www.loom.com/share/a80d3bcb42444a069c0ef03087044e99?sid=b987bebe-c5ed-48d6-8cd5-2ee19985ee3f

**Comment by fvgm-spec** [comment]
Great @aaronsteers thanks for such a great video, it explains a lot on what needs to be covered in the blog post.

**Comment by fvgm-spec** [comment]
Hi @aaronsteers I have made public the [post](https://docs.google.com/document/d/1n_wsguA7-h-sNQKTedfQpYyjaPOONZ_TQMBV2RiuKi0/edit?usp=sharing) intended to explain how to build custom connectors in Airbyte Connector Builder, and then use it in data pipelines with PyAirbyte.

Please let me know the further steps, or if I can continue with another issue from the list. Regards.

**Comment by aaronsteers** [comment]
Hi, @fvgm-spec!  I appreciate your patience in the review. I had a chance to review and the content seems easy to follow and informative. I also appreciate the attachment of notebook to help users reproduce the results.

@bindipankhudi and @marcosmarxm - I'll let you take final review review and begin steps to publish. From my side, the content and technical implementation part looks very good. 👍

**Comment by bindipankhudi** [comment]
Sounds good! I will queue it for publishing @aaronsteers. @fvgm-spec could you share a brief bio for yourself, so we can add that to the blog post.

**Comment by fvgm-spec** [comment]
Hi @bindipankhudi  and @aaronsteers thanks for the review, my bio will be "Felix is a Data Engineer with experience in multiple roles related to Data. He's building his professional identity being an adaptable professional who can navigate constantly changing technological environments."

**Comment by bindipankhudi** [comment]
Awesome! Thank you @fvgm-spec. Will keep you posted as we publish this (in a day or two).

**Comment by bindipankhudi** [comment]
@fvgm-spec , your blog has been published! -  https://airbyte.com/blog/adding-a-custom-source-to-pyairbyte-using-the-no-code-builder 🚀 , it's also accessible in Top stories on [Airbyte blogs ](https://airbyte.com/blog)(on the right side). If you would like to publish it elsewhere, please wait for one week. Thank you! - fyi @marcosmarxm
