### ISSUE TITLE
Debug issues with source-greenhouse connector

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte-Hackathon#8]
## Summary
The Greenhouse source is having issues when run in PyAirbyte. The goal is to replicate and document any observed issues and then propose a fix.

**Comment by Ishankoradia** [comment]
Hi @aaronsteers , I am interested in working on this. 
Could you assign me this please ?

**Comment by marcosmarxm** [comment]
It yours @Ishankoradia

**Comment by Ishankoradia** [comment]
@marcosmarxm can you help with a test `harvest` api key ? I dont see how to any free/trial account registration on Greenhouse.

**Comment by marcosmarxm** [comment]
Can you ping me on Slack please?

**Comment by Ishankoradia** [comment]
> Can you ping me on Slack please?

Pinged you there.

**Comment by btkcodedev** [comment]
Hi @Ishankoradia, As you have already been assigned to https://github.com/airbytehq/PyAirbyte-Hackathon/issues/22, I would like to work on this issue.
Thank you for your understanding
CC: @marcosmarxm @bindipankhudi

**Comment by Ishankoradia** [comment]
I have already started working on both the issues. But I will leave it upto @aaronsteers

**Comment by marcosmarxm** [comment]
@btkcodedev was my mistake to assignee 2 issues, sorry about that.

**Comment by Ishankoradia** [comment]
Hi @marcosmarxm i dont mind if you want to re-assign this one.

I am very deep in the other one "New connector idea: github files".

**Comment by btkcodedev** [comment]
Oh, thanks! I'll take it :)
@marcosmarxm, the other issue PR is handed
Please assign this to me :smile_cat:

**Comment by marcosmarxm** [comment]
@btkcodedev all yours.

**Comment by btkcodedev** [comment]
Checked with Colab, PyAirbyte sync is successful, 
Ref:
![image](https://github.com/airbytehq/PyAirbyte-Hackathon/assets/47392334/a42640df-23cb-42dd-99c9-416f9e8ed31b)

**Comment by btkcodedev** [comment]
Still, connector can be improved,
Linking PR https://github.com/airbytehq/airbyte/pull/39601 
with improvements
